version: '3'

services:
    api:
        build: ./api
        container_name: api
        tty: true
        ports:
            - 8000:8000
        depends_on:
            - redis
        volumes:
            - ./api:/home/project
        
    redis:
        image: redis
        container_name: redis
        expose:
            - 6379
