# Generated by Django 3.1.1 on 2020-09-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='count',
            field=models.IntegerField(default=0, verbose_name='count'),
        ),
    ]
